name: Instagram Bot
on:
  workflow_dispatch: # تشغيل يدوي

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # تحويل الـ Secret إلى ملف JSON حقيقي
      - name: Create Auth File
        run: |
          echo '${{ secrets.INSTA_COOKIES }}' > auth.json
          ls -lh auth.json

      - name: Install dependencies
        run: |
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Run
        run: node upload.js
