name: Instagram Auto Post
on:
  workflow_dispatch: # يتيح لك التشغيل يدوياً بضغطة زر

jobs:
  instagram-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # تحويل الـ Secret إلى ملف حقيقي داخل السيرفر
      - name: Create auth.json from Secret
        run: |
          echo '${{ secrets.INSTA_COOKIES }}' > auth.json
          ls -lh auth.json # للتأكد من حجم الملف في الـ Logs

      - name: Install Dependencies
        run: |
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Run Upload Script
        run: node upload.js
